### ISSUE TITLE
Use rpc to automatically determine what plugins are installed

### ISSUE THREAD

**Issue by fidgetingbits** [hands-free-vim/neovim-talon#12]
My old repo used tags to turn on plugin features, which is nice to avoid having a bunch of stuff you won't use loaded in thr command namespace, but annoying because of how many tags you eventually have to manage. I think talon-vim probably has around 20.

One of my plans was to add support for automatically querying the neovim instance for what plugins are present and then automatically turning on the tags. We could considering doing that since @saidelike you started adding vim_zoom, lazy and taboo. And lazy I don't use for instance. 

I think the trouble would be how do we do it fast enough, since on the surface it seems like everytime we focus on a vim window we'd have to check what plugins exist and enable tags and it might be a bit slow (would have to try to be sure on speed).

One way would be to maintain some sort of state so we set a variable in neovim via talon that says we've scanned it already, and don't try again. The main downside to that is if someone uses lazy say to install a plugin, then it wouldn't automatically pick it up in neovim-talon. This could be solved probably by talon.nvim having callbacks that unset the variable if a plugin gets installed or something.

I guess you don't like the idea of the tags, since you didn't port them over for lazy/taboo/vim_zoom :D

**Comment by saidelike** [comment]
Good idea. We could have a voice command to enforce updating the plugins list to avoid the possible slowness problem you mention.
