### ISSUE TITLE
Fix command server shortcut on Mac

### ISSUE THREAD

**Issue by pokey** [hands-free-vim/neovim-talon#20]
The default command server shortcut didn't work for me; I just heard an error sound and nothing happened. I was able to get `ctrl-q` to work, but that's not ideal because that shortcut has a meaning. We couldn't get anything with `ctrl-shift` to work, which limits our options a bit. We should try to find a good shortcut that is somewhat unique to use as default. It might need to be platform-specific

See also #7

**Comment by saidelike** [comment]
fixed by https://github.com/hands-free-vim/neovim-talon/pull/7
